server:
  tcp_addr: ":53"
  udp_addr: ":53"

dns:
  in: 
    - "8.8.8.8:53"
    - "8.8.4.4:53"
  out:
    - "202.106.0.20:53"
    - "202.96.199.133:53"

rule:
  - baidu.com
  - taobao.com
  - tmall.com
  - etao.com
  - alimama.com
  - alimama.cn
  - jd.com
  - vip.com
  - le.com
  - iqiyi.com
  - qiyi.com
  - sohu.com
  - 163.com
  - qq.com
  - kuwo.cn
  - kugou.com
  - sogou.com
  - weiyun.com
  - weibo.com
  - sina.com
  - sina.com.cn
  - sina.cn
  - 163.com
  - 126.net
  - yhd.com
  - youku.com
  - tudou.com
  - bilibili.com
  - acfun.com
  - 56.com
  - ku6.com
  - aliyun.com
  - 58.com
  - ganji.com
  - meituan.com
