daemon: false
debug: true

server:
  tcp_addr: ":53"
  udp_addr: ":53"

dns:
  in: 
    - "8.8.8.8:53"
    - "8.8.4.4:53"
  out:
    - "202.106.0.20:53"
    - "202.96.199.133:53"

rule:
  - net.cn
  - com.cn
  - baidu.com
  - taobao.com
  - tmall.com
  - etao.com
  - alimama.com
  - alimama.cn
  - jd.com
  - vip.com
  - le.com
  - iqiyi.com
  - qiyi.com
  - sohu.com
  - 163.com
  - qq.com
  - kuwo.cn
  - kugou.com
  - sogou.com
  - weiyun.com
  - weibo.com
  - sina.com.cn
  - sina.cn
  - netease.com
  - 163.com
  - 126.net
  - 127.net
  - yhd.com
  - youku.com
  - tudou.com
  - bilibili.com
  - acfun.tv
  - acfun.cn
  - 56.com
  - ku6.com
  - pptv.com
  - aliyun.com
  - 58.com
  - ganji.com
  - meituan.com
  - douban.com
  - ifeng.com
  - zol.com.cn
  - hao123.com
  - 1688.com
  - pconline.com.cn
  - 2345.com
  - tianya.cn
  - china.com.cn
  - bitauto.com
  - autohome.com.cn
  - ctrip.com
  - fang.com
  - eastmoney.com
  - qidian.com
  - cntv.cn
  - mafengwo.cn
  - xcar.com.cn
  - tvmao.com
  - 360doc.com
  - docin.com
  - onlinedown.net
  - yxdown.com
  - weather.com.cn
  - tianqi.com
  - youth.cn
  - baike.com
  - yesky.com
  - zhihu.com
  - baixing.com
  - pcbaby.com.cn
  - tuniu.com
  - hc360.com
  - 360.cn
  - 4399.com
  - 7k7k.com
  - xiaopi.com
  - 99danji.com
  - 360kan.com
  - so.com
  - uc.cn
  - xueqiu.com
  - xinhuanet.com
  - news.cn
  - zhaopin.com
  - youdao.com
  - dianping.com
  - nuomi.com
  - anjuke.com
  - 17173.com
  - hupu.com
  - 10086.cn
  - 10010.com
  - 189.cn
  - people.com.cn
  - chsi.com.cn
  - pcauto.com.cn
  - gamersky.com
  - mtime.com
  - pcgames.com.cn
  - 52pk.com
  - douwan.com
  - yy.com
  - huya.com
  - zhibo8.cc
  - douyu.tv
  - douyu.com
  - woxiu.com
  - 6.cn
  - longzhu.com
  - zhanqi.tv
  - panda.tv
  - huajiao.com
  - inke.cn
  - inke.tv
  - xiaoka.tv
  - yizhibo.com
  - xiaokaxiu.com
  - miaopai.com
  - aipai.com
  - kaoyan.com
  - kankan.com
  - wasu.cn
  - mi.com
  - uuu9.com
  - cztv.com
  - doyo.cn
  - 1905.com
  - xiami.com
  - 178.com
  - tgbus.com
  - etao.com
  - jjwxc.net
  - 17k.com
  - qunar.com
  - tiexue.net
  - yinyuetai.com
  - mydrivers.com
  - huaban.com
  - pps.tv
  - soku.com
  - u17.com
  - baofeng.com
  - mgtv.com
  - pclady.com.cn
  - ptbus.com
  - mama.cn
  - ly.com
  - 12306.cn
  - tvsou.com
  - southcn.com
  - hujiang.com
  - xdf.cn
  - dangdang.com
  - qdmm.com
  - fun.tv
  - pcpop.com
  - xxsy.net
  - clouddn.com
  - qiniudns.com
  - alidns.com
  - alicdn.com
  - mmstat.com
  - kunlunca.com
  - kunlunar.com
  - kunlunno.com
  - kunlunea.com
  - yunjiasu-cdn.net
  - hichina.com
  - gtimg.com
  - qpic.cn
  - bdstatic.com
  - 360buyimg.com
  - vipstatic.com
  - qbox.me
  - ykimg.com
  - tdimg.com
  - qiyipic.com
  - itc.cn
  - hdslb.com
  - pdim.gs
  - yystatic.com
  - dwstatic.com
  - aixifan.com
